# Animations are calculated in ticks.

animation-duration: 9

animation-speed: 7

# List of available professions:
# ARMORER | BUTCHER | CARTOGRAPHER | CLERIC | FARMER | FISHERMAN | FLETCHER | LEATHERWORKER | LIBRARIAN | MASON | NITWIT | SHEPHERD | TOOLSMITH | WEAPONSMITH
# (NONE to set default NPC)

npc-profession: LIBRARIAN

npc-name: "Lottery"

# Type of item to play (Item used can be anything)

token-type: HEART_OF_THE_SEA

# To add customs colors, simply use color codes like below

fragment-message: "&aCongratulations! &e&l{FRAGMENT}&a fragment added to your ender chest."

reward-message: "&aCongratulations! &e&l{REWARD}&a added to your inventory."

enable-sounds: true

# Particles list: https://mcreator.net/wiki/particles-ids

particles:
  type: FIREWORKS_SPARK
  number: 60
  speed: 0.2

# These items will be displayed in the lottery inventory and in the Ender Chest
# Keys are rewards and values are the number of fragments to get this item

items:
  BLAZE_POWDER: 1
  BLAZE_ROD: 1
  FISHING_ROD: 1
  ELYTRA: 1
  ENDER_PEARL: 1
  GOLDEN_APPLE: 1
  GOLD_INGOT: 1
  DIAMOND: 2
  DIAMOND_AXE: 2
  ENCHANTING_TABLE: 3
  EMERALD: 4
  DIAMOND_HORSE_ARMOR: 4