# Animations are calculated in seconds.

animation-duration: 3

animation-speed: 1

npc-profession: LIBRARIAN

# These items will be display in lottery inventory and in the Ender Chest
# Keys are rewards and values are the number of fragments to get this item

items:
  GOLD_BLOCK: 2
  DIAMOND: 6
  APPLE: 1